name: currere
version: 0.1.0.0
github: "ztk37/currere"
license: MIT
author: "ztk37"
# maintainer: "example@example.com"
copyright: "2022 ztk37 https://github.com/ztk37"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ztk37/currere#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - containers

library:
  source-dirs: lib

executables:
  currere-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - currere

tests:
  currere-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - currere
